In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
# Accedemos a la carpeta de google drive donde tenemos alojados los archivos
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# para ir a la carpeta donde tenemos los datos
os.chdir('/content/drive/MyDrive/Colab Notebooks/')

# Primera parte. Análisis de los competidores.

In [4]:
#Leemos los datos del archivo csv donde hemos recopilado los principales competidores de cada uno de los ecommerce elegidos
# y los almacenamos en variables de tipo dataframe
dfCompetidoresBitiba = pd.read_csv('competidores/competitors_data_for_https___www.bitiba.es.csv', header = 'infer', encoding='utf8')
dfCompetidoresKiwoko = pd.read_csv('competidores/competitors_data_for_https___www.kiwoko.com.csv', header = 'infer', encoding='utf8')
dfCompetidoresMascotaPlanet = pd.read_csv('competidores/competitors_data_for_https___www.mascotaplanet.com.csv', header = 'infer', encoding='utf8')
dfCompetidoresMascoteros = pd.read_csv('competidores/competitors_data_for_https___www.mascoteros.com.csv', header = 'infer', encoding='utf8')
dfCompetidoresMiscota = pd.read_csv('competidores/competitors_data_for_https___www.miscota.es.csv', header = 'infer', encoding='utf8')
dfCompetidoresNuestroPerro = pd.read_csv('competidores/competitors_data_for_https___www.nuestroperro.es.csv', header = 'infer', encoding='utf8')
dfCompetidoresPetclic = pd.read_csv('competidores/competitors_data_for_https___www.petclic.es.csv', header = 'infer', encoding='utf8')
dfCompetidoresPiensoyMascotas = pd.read_csv('competidores/competitors_data_for_https___www.piensoymascotas.com.csv', header = 'infer', encoding='utf8')
dfCompetidoresTiendanimal = pd.read_csv('competidores/competitors_data_for_https___www.tiendanimal.es.csv', header = 'infer', encoding='utf8')

In [5]:
# Creamos una variable de tipo diccionario con los valores de los que hemos partido
# donde iremos almacenando los datos de frecuencia de competidores que aparecen en los
# datos que hemos cargado
diccionario = {
    "bitiba.es": 1,
    "kiwoko.com": 1,
    "mascotaplanet.com": 1,
    "mascoteros.com": 1,
    "miscota.es": 1,
    "nuestroperro.es": 1,
    "petclic.es": 1,
    "piensoymascotas.com": 1,
    "tiendanimal.es": 1
}

# creamos una función a la que le pasaremos cada dataframe
def creaDiccionario (df):
  # recorremos por filas el dataframe
  for i in df.index:
    # para cada fila de la columna donde aparece la información del dominio de la competencia
    # si no está en el diccionario lo añadimos con valor uno por su primera aparición
    if df['Dominio de la competencia'][i] not in diccionario:
      diccionario[df['Dominio de la competencia'][i]] = 1
    # si ya está en el diccionario, entonces incrementamos en uno el valor
    else:
      diccionario[df['Dominio de la competencia'][i]] += 1

# a continuación pasamos cada uno de los dataframe por la función para que cree el diccionario
creaDiccionario(dfCompetidoresBitiba)
creaDiccionario(dfCompetidoresKiwoko)
creaDiccionario(dfCompetidoresMascotaPlanet)
creaDiccionario(dfCompetidoresMascoteros)
creaDiccionario(dfCompetidoresMiscota)
creaDiccionario(dfCompetidoresNuestroPerro)
creaDiccionario(dfCompetidoresPetclic)
creaDiccionario(dfCompetidoresPiensoyMascotas)
creaDiccionario(dfCompetidoresTiendanimal)

In [6]:
# imprimimos el diccionario para comprobar que todo es correcto
print(diccionario)

{'bitiba.es': 4, 'kiwoko.com': 9, 'mascotaplanet.com': 1, 'mascoteros.com': 3, 'miscota.es': 9, 'nuestroperro.es': 1, 'petclic.es': 2, 'piensoymascotas.com': 6, 'tiendanimal.es': 9, 'zooplus.es': 9, 'zoomalia.es': 9, 'carrefour.es': 4, 'elcorteingles.es': 7, 'gatostienda.es': 6, 'maskokotas.com': 4, 'idealo.es': 2, 'piensosraposo.es': 2, 'para-gatos.net': 1, 'royalcanin.com': 2, 'hillspet.es': 3, 'milanuncios.com': 6, 'expertoanimal.com': 7, 'mundodeportivo.com': 5, 'perrostienda.es': 6, 'purina.es': 2, 'redcanina.es': 4, 'aliexpress.com': 4, 'huellacanina.com': 3, 'wallapop.com': 1, 'muyinteresante.es': 1, 'affinity-petcare.com': 1, 'animalear.com': 1, 'mascotapro.com': 1, 'perrogato.net': 1, 'petsfarma.es': 3, 'hola.com': 1, 'soyunperro.com': 1, 'paginasamarillas.es': 1, 'cylex.es': 1, 'barakaldotiendaveterinaria.es': 1}

In [7]:
df = pd.DataFrame([[key, diccionario[key]] for key in diccionario.keys()], columns=['Competidor', 'Apariciones'])
df.sort_values(by='Apariciones', ascending=False)

                       Competidor  Apariciones
1                      kiwoko.com            9
4                      miscota.es            9
8                  tiendanimal.es            9
9                      zooplus.es            9
10                    zoomalia.es            9
21              expertoanimal.com            7
12               elcorteingles.es            7
20                milanuncios.com            6
23                perrostienda.es            6
7             piensoymascotas.com            6
13                 gatostienda.es            6
22             mundodeportivo.com            5
26                 aliexpress.com            4
25                   redcanina.es            4
0                       bitiba.es            4
14                 maskokotas.com            4
11                   carrefour.es            4
27               huellacanina.com            3
34                   petsfarma.es            3
19                    hillspet.es            3
3                  mascoteros.com            3
24                      purina.es            2
16               piensosraposo.es            2
15                      idealo.es            2
6                      petclic.es            2
18                 royalcanin.com            2
5                 nuestroperro.es            1
2               mascotaplanet.com            1
28                   wallapop.com            1
29              muyinteresante.es            1
30           affinity-petcare.com            1
31                  animalear.com            1
32                 mascotapro.com            1
33                  perrogato.net            1
17                 para-gatos.net            1
35                       hola.com            1
36                 soyunperro.com            1
37            paginasamarillas.es            1
38                       cylex.es            1
39  barakaldotiendaveterinaria.es            1

# Segunda Parte. Análisis de palabras clave.

En esta parte vamos a buscar cuál es la palabra clave que tienen en común y por la que compiten en los resultados de las SERPS los principales competidores con los criterios que hemos elegido, en este caso, que sean ecommerce.

In [11]:
#Leemos los datos del archivo csv donde hemos recopilado las principales keywords por las que estan posicionadas las webs competidoras entre si
dfKeywordsAnimalear = pd.read_csv('keywords/ubersuggest_www.animalear.com.csv', header = 'infer', encoding='utf8')
dfKeywordsBarakaldoTiendaVeterinaria = pd.read_csv('keywords/ubersuggest_www.barakaldotiendaveterinaria.es.csv', header = 'infer', encoding='utf8')
dfKeywordsBitiba = pd.read_csv('keywords/ubersuggest_www.bitiba.es.csv', header = 'infer', encoding='utf8')
dfKeywordsHuellaCanina = pd.read_csv('keywords/ubersuggest_www.huellacanina.com.csv', header = 'infer', encoding='utf8')
dfKeywordsKiwoko = pd.read_csv('keywords/ubersuggest_www.kiwoko.com.csv', header = 'infer', encoding='utf8')
dfKeywordsMascotaPlanet = pd.read_csv('keywords/ubersuggest_www.mascotaplanet.com.csv', header = 'infer', encoding='utf8')
dfKeywordsMascoteros = pd.read_csv('keywords/ubersuggest_www.mascoteros.com.csv', header = 'infer', encoding='utf8')
dfKeywordsMaskokotas = pd.read_csv('keywords/ubersuggest_www.maskokotas.com.csv', header = 'infer', encoding='utf8')
dfKeywordsMiscota = pd.read_csv('keywords/ubersuggest_www.miscota.es.csv', header = 'infer', encoding='utf8')
dfKeywordsNuestroPerro = pd.read_csv('keywords/ubersuggest_www.nuestroperro.es.csv', header = 'infer', encoding='utf8')
dfKeywordsPerroGato = pd.read_csv('keywords/ubersuggest_www.perrogato.net.csv', header = 'infer', encoding='utf8')
dfKeywordsPetclic = pd.read_csv('keywords/ubersuggest_www.petclic.es.csv', header = 'infer', encoding='utf8')
dfKeywordsPetsfarma = pd.read_csv('keywords/ubersuggest_www.petsfarma.es.csv', header = 'infer', encoding='utf8')
dfKeywordsPiensosRaposo = pd.read_csv('keywords/ubersuggest_www.piensosraposo.es.csv', header = 'infer', encoding='utf8')
dfKeywordsPiensoyMascotas = pd.read_csv('keywords/ubersuggest_www.piensoymascotas.com.csv', header = 'infer', encoding='utf8')
dfKeywordsTiendanimal = pd.read_csv('keywords/ubersuggest_www.tiendanimal.es.csv', header = 'infer', encoding='utf8')
dfKeywordsZoomalia = pd.read_csv('keywords/ubersuggest_www.zoomalia.es.csv', header = 'infer', encoding='utf8')
dfKeywordsZooplus = pd.read_csv('keywords/ubersuggest_www.zooplus.es.csv', header = 'infer', encoding='utf8')

# guardamos en una lista todos los archivos de datos a modo de indice
listaDatos =[dfKeywordsAnimalear, dfKeywordsBarakaldoTiendaVeterinaria, dfKeywordsBitiba, dfKeywordsHuellaCanina, dfKeywordsKiwoko, dfKeywordsMascotaPlanet,
          dfKeywordsMascoteros, dfKeywordsMaskokotas, dfKeywordsMiscota, dfKeywordsNuestroPerro, dfKeywordsPerroGato, dfKeywordsPetclic, dfKeywordsPetsfarma,
          dfKeywordsPiensosRaposo, dfKeywordsPiensoyMascotas, dfKeywordsTiendanimal, dfKeywordsZoomalia, dfKeywordsZooplus]
listaNombres =['animalear.com', 'barakaldotiendaveterinaria.es', 'bitiba.es', 'huellacanina.com', 'kiwoko.com', 'mascotaplanet.com', 'mascoteros.com', 'maskokotas.com', 'miscota.es',
               'nuestroperro.es', 'perrogato.net', 'petclic.es', 'petsfarma.es','piensosraposo.es', 'piensoymascotas.com', 'tiendanimal.es', 'zoomalia.es', 'zooplus.es']

In [12]:
#Comprobamos como se ven los datos en los dataframes
dfKeywordsAnimalear

      No                 Palabras clave  ...  Est Visitas  SEO Difficulty
0      1                  animalear app  ...           29              68
1      2               animalear tienda  ...           29              43
2      3        animalear tienda fisica  ...           14              43
3      4        animalear tienda física  ...           14              43
4      5             animalear telefono  ...           19              32
..   ...                            ...  ...          ...             ...
212  213        tienda de gatos sevilla  ...            0              53
213  214         comprar gatos mallorca  ...            0              51
214  215        ropa de animales online  ...            0               4
215  216        tienda animales cordoba  ...            0              39
216  217  tienda de animales en almeria  ...            0              50

[217 rows x 6 columns]

In [13]:
#Visualizamos la cantidad de datos que hay en cado uno de los dataframes
print('El número de keywords en Animalear es:', dfKeywordsAnimalear.shape)
print('El número de keywords en BarakaldoTiendaVeterinaria es:', dfKeywordsBarakaldoTiendaVeterinaria.shape)
print('El número de keywords en Bitiba es:', dfKeywordsBitiba.shape)
print('El número de keywords en HuellaCanina es:', dfKeywordsHuellaCanina.shape)
print('El número de keywords en Kiwoko es:', dfKeywordsKiwoko.shape)
print('El número de keywords en MascotaPlanet es:', dfKeywordsMascotaPlanet.shape)
print('El número de keywords en Mascoteros es:', dfKeywordsMascoteros.shape)
print('El número de keywords en Maskokotas es:', dfKeywordsMaskokotas.shape)
print('El número de keywords en Miscota es:', dfKeywordsMiscota.shape)
print('El número de keywords en NuestroPerro es:', dfKeywordsNuestroPerro.shape)
print('El número de keywords en PerroGato es:', dfKeywordsPerroGato.shape)
print('El número de keywords en Petclic es:', dfKeywordsPetclic.shape)
print('El número de keywords en Petsfarma es:', dfKeywordsPetsfarma.shape)
print('El número de keywords en PiensosRaposo es:', dfKeywordsPiensosRaposo.shape)
print('El número de keywords en PiensoyMascotas es:', dfKeywordsPiensoyMascotas.shape)
print('El número de keywords en Tiendanimal es:', dfKeywordsTiendanimal.shape)
print('El número de keywords en Zoomalia es:', dfKeywordsZoomalia.shape)
print('El número de keywords en Zooplus es:', dfKeywordsZooplus.shape)

El número de keywords en Animalear es: (217, 6)
El número de keywords en BarakaldoTiendaVeterinaria es: (2093, 6)
El número de keywords en Bitiba es: (454, 6)
El número de keywords en HuellaCanina es: (809, 6)
El número de keywords en Kiwoko es: (8816, 6)
El número de keywords en MascotaPlanet es: (379, 6)
El número de keywords en Mascoteros es: (703, 6)
El número de keywords en Maskokotas es: (983, 6)
El número de keywords en Miscota es: (2173, 6)
El número de keywords en NuestroPerro es: (128, 6)
El número de keywords en PerroGato es: (136, 6)
El número de keywords en Petclic es: (427, 6)
El número de keywords en Petsfarma es: (712, 6)
El número de keywords en PiensosRaposo es: (754, 6)
El número de keywords en PiensoyMascotas es: (648, 6)
El número de keywords en Tiendanimal es: (8852, 6)
El número de keywords en Zoomalia es: (862, 6)
El número de keywords en Zooplus es: (5227, 6)

## 2.1. Palabras clave

In [14]:
# Creamos una variable de tipo diccionario donde iremos guardando todas las palabras clave que hay entre todos los competidores
# y además iremos guardando el número de veces que se repite para localizar todos los competidores que compiten por la misma palabra clave
keywords = {}

# creamos una función a la que le pasaremos cada dataframe de cada dominio
def creaKeywords (dfk, n):
  # recorremos por filas el dataframe
  for i in dfk.index:
    # para cada fila de la columna donde aparece la información de la palabra clave
    # si no está en el diccionario lo añadimos con valor uno por su primera aparición y almacenamos también el volumen de búsquedas
    if dfk['Palabras clave'][i] not in keywords:
      keywords[dfk['Palabras clave'][i]] = {'Sitio Web': listaNombres[n],'Aparición': 0,'Volumen': dfk['Volumen'][i], 'Estimación Visitas': dfk['Est Visitas'][i], 'Posición': dfk['Posición'][i]}
    # si ya está en el diccionario, entonces incrementamos en uno el valor de la aparición
    # el volumen de búsquedas se deja como está pues va a ser el mismo para la misma keyword
    else:
      keywords[dfk['Palabras clave'][i]]['Aparición'] += 1

# a continuación pasamos cada uno de los dataframe por la función  creada creaKeywords junto con el indice de webs para que cree el diccionario completo de palabras clave
indice = 0
for lista in listaDatos:
  creaKeywords(lista, indice)
  indice += 1

In [15]:
# Pasamos el diccionario que hemos creado a un dataframe
dfKeywords = pd.DataFrame([key for key in keywords.keys()], columns=['Palabras Clave'])
dfKeywords['Aparición'] = [value['Aparición'] for value in keywords.values()]
dfKeywords['Volumen'] = [value['Volumen'] for value in keywords.values()]
dfKeywords

                          Palabras Clave  Aparición  Volumen
0                          animalear app          0       90
1                       animalear tienda          0       70
2                animalear tienda fisica          0       40
3                animalear tienda física          0       40
4                     animalear telefono          0      170
...                                  ...        ...      ...
23360                envio sobres barato          0      110
23361                  jugueterias gijon          0      480
23362                reptiles en sevilla          0       90
23363  tiendas de juguetes en las palmas          0       90
23364             venta de perro pequeño          0      480

[23365 rows x 3 columns]

In [16]:
# ordenamos el dataframe creado por cantidad de veces que aparece una palabra clave en orden ascendente
# y mostramos los primeros diez resultados
dfKeywordsOrdenado = dfKeywords.sort_values(by='Aparición', ascending=False)
dfKeywordsOrdenado.head(10)

                   Palabras Clave  Aparición  Volumen
388  comprar pienso perros online         16       70
31             tienda para perros         16      720
168     tienda online para perros         16       90
23                  tienda perros         16     1900
468          pienso perros online         16       90
423   comprar pienso perro online         16       70
42              tiendas de perros         16     2400
46      tienda online de mascotas         15      480
56          tienda animales gatos         15       70
833  tiendas mascotas cerca de mi         15      720

Vemos que hay varias palabras clave que se repiten entre los 16 de los 18 competidores que estamos analizando. Entre ellas la palabra clave **'tiendas de perros'** es la que más volumen de búsquedas mensuales tiene, asi que la elegimos para obtener el ranking de posiciones.

# 3. Ranking de competidores para la palabra clave elegida

In [17]:
# Creamos una variable de tipo diccionario donde iremos almacenando todos los datos extraidos
ranking = {}
# Guardamos en una variable nuestra palabra clave objetivo
keyword = 'tiendas de perros'
# creamos una función a la que le pasaremos cada archivo de datos de cada uno de los competidores
def creaRanking (df, n):
  # recorremos por filas el dataframe
  for i in df.index:
    if df['Palabras clave'][i] == keyword:
      ranking[df['Posición'][i]] = {'Sitio Web': listaNombres[n], 'Palabras Clave': df['Palabras clave'][i], 'Volumen': df['Volumen'][i], 'Posición': df['Posición'][i]}

indice = 0
for lista in listaDatos:
  creaRanking(lista, indice)
  indice += 1

ranking

{1: {'Palabras Clave': 'tiendas de perros',
  'Posición': 1,
  'Sitio Web': 'zooplus.es',
  'Volumen': 2400},
 2: {'Palabras Clave': 'tiendas de perros',
  'Posición': 2,
  'Sitio Web': 'kiwoko.com',
  'Volumen': 2400},
 3: {'Palabras Clave': 'tiendas de perros',
  'Posición': 3,
  'Sitio Web': 'miscota.es',
  'Volumen': 2400},
 4: {'Palabras Clave': 'tiendas de perros',
  'Posición': 4,
  'Sitio Web': 'tiendanimal.es',
  'Volumen': 2400},
 6: {'Palabras Clave': 'tiendas de perros',
  'Posición': 6,
  'Sitio Web': 'maskokotas.com',
  'Volumen': 2400},
 8: {'Palabras Clave': 'tiendas de perros',
  'Posición': 8,
  'Sitio Web': 'mascoteros.com',
  'Volumen': 2400},
 9: {'Palabras Clave': 'tiendas de perros',
  'Posición': 9,
  'Sitio Web': 'zoomalia.es',
  'Volumen': 2400},
 14: {'Palabras Clave': 'tiendas de perros',
  'Posición': 14,
  'Sitio Web': 'bitiba.es',
  'Volumen': 2400},
 15: {'Palabras Clave': 'tiendas de perros',
  'Posición': 15,
  'Sitio Web': 'petclic.es',
  'Volumen': 2400},
 21: {'Palabras Clave': 'tiendas de perros',
  'Posición': 21,
  'Sitio Web': 'nuestroperro.es',
  'Volumen': 2400},
 34: {'Palabras Clave': 'tiendas de perros',
  'Posición': 34,
  'Sitio Web': 'animalear.com',
  'Volumen': 2400},
 39: {'Palabras Clave': 'tiendas de perros',
  'Posición': 39,
  'Sitio Web': 'barakaldotiendaveterinaria.es',
  'Volumen': 2400},
 47: {'Palabras Clave': 'tiendas de perros',
  'Posición': 47,
  'Sitio Web': 'piensoymascotas.com',
  'Volumen': 2400},
 82: {'Palabras Clave': 'tiendas de perros',
  'Posición': 82,
  'Sitio Web': 'piensosraposo.es',
  'Volumen': 2400},
 84: {'Palabras Clave': 'tiendas de perros',
  'Posición': 84,
  'Sitio Web': 'perrogato.net',
  'Volumen': 2400},
 89: {'Palabras Clave': 'tiendas de perros',
  'Posición': 89,
  'Sitio Web': 'huellacanina.com',
  'Volumen': 2400}}

In [18]:
# Pasamos el diccionario que hemos creado a un dataframe
dfRanking = pd.DataFrame([key for key in ranking.keys()], columns=['Sitio Web'])
dfRanking['Palabras Clave'] = [value['Palabras Clave'] for value in ranking.values()]
dfRanking['Sitio Web'] = [value['Sitio Web'] for value in ranking.values()]
dfRanking['Posición'] = [value['Posición'] for value in ranking.values()]
dfRanking

                        Sitio Web     Palabras Clave  Posición
0                   animalear.com  tiendas de perros        34
1   barakaldotiendaveterinaria.es  tiendas de perros        39
2                       bitiba.es  tiendas de perros        14
3                huellacanina.com  tiendas de perros        89
4                      kiwoko.com  tiendas de perros         2
5                  mascoteros.com  tiendas de perros         8
6                  maskokotas.com  tiendas de perros         6
7                      miscota.es  tiendas de perros         3
8                 nuestroperro.es  tiendas de perros        21
9                   perrogato.net  tiendas de perros        84
10                     petclic.es  tiendas de perros        15
11               piensosraposo.es  tiendas de perros        82
12            piensoymascotas.com  tiendas de perros        47
13                 tiendanimal.es  tiendas de perros         4
14                    zoomalia.es  tiendas de perros         9
15                     zooplus.es  tiendas de perros         1

In [19]:
# ordenamos el dataframe creado por ranking en orden ascendente
dfRankingOrdenado = dfRanking.sort_values(by='Posición', ascending=True)
dfRankingOrdenado.head(10)

          Sitio Web     Palabras Clave  Posición
15       zooplus.es  tiendas de perros         1
4        kiwoko.com  tiendas de perros         2
7        miscota.es  tiendas de perros         3
13   tiendanimal.es  tiendas de perros         4
6    maskokotas.com  tiendas de perros         6
5    mascoteros.com  tiendas de perros         8
14      zoomalia.es  tiendas de perros         9
2         bitiba.es  tiendas de perros        14
10       petclic.es  tiendas de perros        15
8   nuestroperro.es  tiendas de perros        21

Hemos obtenido el ranking de posiciones de nuestros 10 competidores para la palabra clave escogida y que analizaremos en profundidad

# 4. Autoridad del Dominio y Backlinks
Para la palabra clave elegida obtenemos los resultados de los 100 resultados de búsqueda, obtenemos de esta parte la autoridad de dominio y la cantidad de enlaces que apuntan a cada uno de los dominios o backlinks

In [20]:
#Creamos una variable que almacena los diez competidores elegidos
listaCompetidores =['bitiba.es', 'kiwoko.com', 'mascoteros.com', 'maskokotas.com', 'miscota.es',
               'nuestroperro.es', 'petclic.es', 'tiendanimal.es', 'zoomalia.es', 'zooplus.es']
#Leemos los datos del archivo csv donde hemos recopilado las 100 SERPS
dfSERPS = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/serps/ubersuggest_SERP_analysis.csv', header = 'infer', encoding='utf8')
dfSERPS

     No                                             Titulo  ... Compartidas  DA
0     1    Kiwoko Mundo Animal | Tienda de animales online  ...      10.491  54
1     2  zooplus - Tu tienda para mascotas online líder...  ...      11.898  52
2     3   Miscota: Tu tienda online de mascotas y animales  ...      10.472  43
3     4  Tiendanimal: Tienda Online de productos y comi...  ...      35.813  64
4     5  - Comprar perros y cachorros. Consulta precio ...  ...       6.000  17
..  ...                                                ...  ...         ...  ..
95   96        Tienda de Accesorios para Perro | Decathlon  ...       0.000  75
96   97            Tienda de animales Petsworld Torrevieja  ...       0.000  18
97   98  Agroanimal: Tienda online de productos para an...  ...       0.000  16
98   99            Tienda para mascotas - Alcudia Magatzem  ...       0.000   4
99  100                      Comotú Mascotas | Plaza Mar 2  ...       0.000  28

[100 rows x 8 columns]

In [21]:
# Creamos una variable de tipo diccionario donde iremos almacenando todos los datos extraidos de los competidores a estudiar
serps = {}

# creamos una función a la que le pasaremos cada archivo de datos de cada uno de los competidores
def creaSerps (df, n):
  # recorremos por filas el dataframe
  for i in df.index:
    if df['Dominio'][i] == listaCompetidores[n]:
      serps[df['Dominio'][i]] = {'Sitio Web': listaCompetidores[n], 'Autoridad de Dominio': df['DA'][i], 'Enlaces': df['Enlaces'][i], 'URL': df['URL'][i], 'Visitas': df['Visitas'][i],}

indice = 0
for lista in listaCompetidores:
  creaSerps(dfSERPS, indice)
  indice += 1

serps

{'bitiba.es': {'Autoridad de Dominio': 32,
  'Enlaces': 86.58200000000001,
  'Sitio Web': 'bitiba.es',
  'URL': 'http://www.bitiba.es/',
  'Visitas': 3},
 'kiwoko.com': {'Autoridad de Dominio': 54,
  'Enlaces': 18.618,
  'Sitio Web': 'kiwoko.com',
  'URL': 'http://www.kiwoko.com/',
  'Visitas': 729},
 'mascoteros.com': {'Autoridad de Dominio': 48,
  'Enlaces': 5.694,
  'Sitio Web': 'mascoteros.com',
  'URL': 'http://www.mascoteros.com/',
  'Visitas': 0},
 'maskokotas.com': {'Autoridad de Dominio': 35,
  'Enlaces': 267.0,
  'Sitio Web': 'maskokotas.com',
  'URL': 'http://www.maskokotas.com/',
  'Visitas': 47},
 'miscota.es': {'Autoridad de Dominio': 43,
  'Enlaces': 50.958999999999996,
  'Sitio Web': 'miscota.es',
  'URL': 'http://www.miscota.es/',
  'Visitas': 233},
 'nuestroperro.es': {'Autoridad de Dominio': 32,
  'Enlaces': 6.385,
  'Sitio Web': 'nuestroperro.es',
  'URL': 'http://www.nuestroperro.es/',
  'Visitas': 2},
 'petclic.es': {'Autoridad de Dominio': 36,
  'Enlaces': 35.264,
  'Sitio Web': 'petclic.es',
  'URL': 'http://www.petclic.es/',
  'Visitas': 0},
 'tiendanimal.es': {'Autoridad de Dominio': 64,
  'Enlaces': 123.07600000000001,
  'Sitio Web': 'tiendanimal.es',
  'URL': 'http://www.tiendanimal.es/',
  'Visitas': 158},
 'zoomalia.es': {'Autoridad de Dominio': 30,
  'Enlaces': 200.423,
  'Sitio Web': 'zoomalia.es',
  'URL': 'http://www.zoomalia.es/',
  'Visitas': 61},
 'zooplus.es': {'Autoridad de Dominio': 52,
  'Enlaces': 297.657,
  'Sitio Web': 'zooplus.es',
  'URL': 'http://www.zooplus.es/',
  'Visitas': 388}}

In [22]:
# Pasamos el diccionario que hemos creado a un dataframe
dfSerps = pd.DataFrame([key for key in serps.keys()], columns=['Sitio Web'])
dfSerps['URL destino'] = [value['URL'] for value in serps.values()]
dfSerps['Enlaces'] = [value['Enlaces'] for value in serps.values()]
dfSerps['Autoridad de Dominio'] = [value['Autoridad de Dominio'] for value in serps.values()]
dfSerps['Visitas'] = [value['Visitas'] for value in serps.values()]
dfSerps

         Sitio Web                  URL destino  ...  Autoridad de Dominio  Visitas
0        bitiba.es        http://www.bitiba.es/  ...                    32        3
1       kiwoko.com       http://www.kiwoko.com/  ...                    54      729
2   mascoteros.com   http://www.mascoteros.com/  ...                    48        0
3   maskokotas.com   http://www.maskokotas.com/  ...                    35       47
4       miscota.es       http://www.miscota.es/  ...                    43      233
5  nuestroperro.es  http://www.nuestroperro.es/  ...                    32        2
6       petclic.es       http://www.petclic.es/  ...                    36        0
7   tiendanimal.es   http://www.tiendanimal.es/  ...                    64      158
8      zoomalia.es      http://www.zoomalia.es/  ...                    30       61
9       zooplus.es       http://www.zooplus.es/  ...                    52      388

[10 rows x 5 columns]

In [23]:
# ordenamos el dataframe creado por estimación de visitas en orden descendente
dfSerpsOrdenado = dfSerps.sort_values(by='Visitas', ascending=False)
dfSerpsOrdenado.head(10)

         Sitio Web                  URL destino  ...  Autoridad de Dominio  Visitas
1       kiwoko.com       http://www.kiwoko.com/  ...                    54      729
9       zooplus.es       http://www.zooplus.es/  ...                    52      388
4       miscota.es       http://www.miscota.es/  ...                    43      233
7   tiendanimal.es   http://www.tiendanimal.es/  ...                    64      158
8      zoomalia.es      http://www.zoomalia.es/  ...                    30       61
3   maskokotas.com   http://www.maskokotas.com/  ...                    35       47
0        bitiba.es        http://www.bitiba.es/  ...                    32        3
5  nuestroperro.es  http://www.nuestroperro.es/  ...                    32        2
2   mascoteros.com   http://www.mascoteros.com/  ...                    48        0
6       petclic.es       http://www.petclic.es/  ...                    36        0

[10 rows x 5 columns]

A partir de esta tabla podemos obtener los datos de backlinks y la autoridad de dominio.

# 4. Calculo del CTR
Para calcular el CTR estimado sabemos que para esta palabra clave teniamos un volumen de búsquedas mensuales de 2400, asi que basta con tomar la columna de visitas estimadas y calcular el porcentaje de visitas entre el volumen de búsquedas mensuales para obtener un CTR estimado

In [24]:
# Añadimos una nueva columna con el cálculo y redondeamos a dos decimales
dfSerps['CTR'] = round((dfSerps['Visitas']/2400)*100, 2)
dfSerps

         Sitio Web                  URL destino  ...  Visitas    CTR
0        bitiba.es        http://www.bitiba.es/  ...        3   0.12
1       kiwoko.com       http://www.kiwoko.com/  ...      729  30.38
2   mascoteros.com   http://www.mascoteros.com/  ...        0   0.00
3   maskokotas.com   http://www.maskokotas.com/  ...       47   1.96
4       miscota.es       http://www.miscota.es/  ...      233   9.71
5  nuestroperro.es  http://www.nuestroperro.es/  ...        2   0.08
6       petclic.es       http://www.petclic.es/  ...        0   0.00
7   tiendanimal.es   http://www.tiendanimal.es/  ...      158   6.58
8      zoomalia.es      http://www.zoomalia.es/  ...       61   2.54
9       zooplus.es       http://www.zooplus.es/  ...      388  16.17

[10 rows x 6 columns]